### ISSUE TITLE
Breadcrumbs need better padding

### ISSUE THREAD

**Issue by yochannah** [OBF/homepage#16]
example: https://www.open-bio.org/events/bosc/bosc-2019-keynote-building-infrastructure-for-responsible-open-science-in-africa/ - breadcrumbs touch the left of the page edge.

**Comment by yochannah** [comment]
this is only for very long page titles and I think is session or history based as the long breadcrumbes don't always show up?

**Comment by peterjc** [comment]
Closed via #21

**Comment by peterjc** [comment]
It should be closed - I should probably wait for the page to update before closing.

**Comment by yochannah** [comment]
this is deployed now :)
