### ISSUE TITLE
homepage content - too wide for single column text pages

### ISSUE THREAD

**Issue by yochannah** [OBF/homepage#18]
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/9271438/57781181-993c4200-7721-11e9-8449-80f0e847f0bb.png">

See screenshot above - should have a maximum width with padding on both sides for wider screens. Also suggest we try a easier-to-read font, possibly arial.

**Comment by heuermh** [comment]
There should also be more whitespace vertically between paragraphs/blocks, and slightly larger line height compared to font size, especially for lists (OL, UL).

**Comment by peterjc** [comment]
Deployed, most of that seems to be working nicely - a big improvement for me on the text heavy pages.

@heuermh are you happy with the lists now (OL, UL)?

**Comment by heuermh** [comment]
I'm not sure the list changes applied all across the site, note the difference here between the Important Dates and Section Topics lists.  Or perhaps some other formatting constraints are happening there, to make both blocks the same height.

<img width="1355" alt="screenshot" src="https://user-images.githubusercontent.com/35293/58490606-15c41d00-8133-11e9-8e4b-8f94cc3bd64b.png">

**Comment by peterjc** [comment]
Can we apply the width changes to the blog pages too?, e.g.
https://www.open-bio.org/2019/05/31/travel-award-recipients-for-april-2019/

**Comment by yochannah** [comment]
fixed as part of #28
