### ISSUE TITLE
Avoid all capital section formatting?

### ISSUE THREAD

**Issue by peterjc** [OBF/homepage#19]
e.g. https://www.open-bio.org/events/bosc/collaborationfest/ where the mixed case in CoFest or CollaborationFest is lost.

**Comment by nlharris** [comment]
Yeah, I kind of hate the all-caps too.

**Comment by heuermh** [comment]
All of the margins/padding/spacing around header tags (H1, H2, H3, ...) need adjusting.  There should be significantly more whitespace on top and more whitespace on the bottom.

**Comment by peterjc** [comment]
I think you’re right - certainly a little more vertical space above section titles would help.

(It makes sense to discuss that here since it will likely be the same style definitions to tweak)

**Comment by peterjc** [comment]
There is evidently some deployment step needed after the git merge - which from the ``README.md`` file alone I do not understand. Yo?

**Comment by yochannah** [comment]
We'll need @hlapp to do the deploy as there isn't an auto pipeline in place.

**Comment by peterjc** [comment]
Documenting deployment logged as #23 (sorry I moved my earlier comment to #21).

**Comment by peterjc** [comment]
Deployed, closing. Thanks all.
