### ISSUE TITLE
Add sponsors to open-bio.org/events/bosc/collaborationfest

### ISSUE THREAD

**Issue by heuermh** [OBF/homepage#20]
See https://github.com/OBF/homepage/issues/17#issuecomment-494464505

**Comment by peterjc** [comment]
AWS logos here (although we have one on the server already which is likely the same bitmap):

https://boofcode.s3.amazonaws.com/files/AWS%20Print%20Quality%20Logos.zip

**Comment by peterjc** [comment]
Closed, thank you Alex.

**Comment by peterjc** [comment]
Thanks due to @apeltzer 👍
