### ISSUE TITLE
Change bosc-announce link in footer

### ISSUE THREAD

**Issue by nlharris** [OBF/homepage#26]
The link to the bosc-announce mailing list from the letter icon in the footer should be changed to https://groups.google.com/forum/#!forum/bosc-announce

**Comment by nlharris** [comment]
Issue #12 is related.

**Comment by nlharris** [comment]
@yochannah if you can remind me how to edit the footer i can do this myself...

**Comment by yochannah** [comment]
Main footer: https://github.com/OBF/homepage/blob/master/footer.php
BOSC footer: https://github.com/OBF/homepage/blob/master/footer-bosc.php
