### ISSUE TITLE
Convert footer to widget area

### ISSUE THREAD

**Issue by yochannah** [OBF/homepage#3]
https://github.com/OBF/homepage/blob/b1024c78e05035485a3ab84f7a1bde28c9a900c8/footer-bosc.php 

the content in the footer should be editable - can we make it a widget area?

https://codex.wordpress.org/Widgetizing_Themes

**Comment by nlharris** [comment]
Is this so we can fix the issue with the hashtag wrapping in the footer? 
![Screen Shot 2019-03-13 at 9 27 49 PM](https://user-images.githubusercontent.com/348704/54331419-2a365600-45d7-11e9-8496-865a5d3e4d6a.png)
(weirdly, the wrapping seems to have changed slightly--it's now #bosc20  19 but the other day I'm pretty sure it was #bosc201  9!)

**Comment by yochannah** [comment]
It's why I noticed it, but not quite the same thing - we don't want to have to edit the theme code to change that hashtag, for example - it would be better to be able to have it managed by the CMS.

**Comment by yochannah** [comment]
fixed as part of #35
