### ISSUE TITLE
Add OBF membership page to menu bar

### ISSUE THREAD

**Issue by nlharris** [OBF/homepage#30]
I  just noticed that the About OBF page said, "The OBF is open to anyone who is interested in promoting open source bioinformatics / open science. Please see the Membership page for more information." -- and there was no link to the Membership page! So I added one, but it still seems like this should be on the menu bar (perhaps under About).

**Comment by yochannah** [comment]
added under about! 

for reference, this can be managed under appearance > menus  - and then select either the bosc menu or the main menu

**Comment by nlharris** [comment]
oh yeah, i forgot 🙈
thanks!
