### ISSUE TITLE
Add posters to schedule page

### ISSUE THREAD

**Issue by nlharris** [OBF/homepage#31]
Add a table of posters to https://www.open-bio.org/events/bosc/schedule/ (see https://www.open-bio.org/wiki/BOSC_2017_Schedule for an example). @cjfields is this something you could take on? And perhaps @yochannah could help us to set it up to suck in a gsheet as for the talk schedule?

**Comment by yochannah** [comment]
Sure, let me know when the poster slreadsheet list is ready and I'll glue
it in to the homepage!

**Comment by yochannah** [comment]
The, err, slreadsheet, is added. :)
