### ISSUE TITLE
Add "at a glance" schedule overview to schedule page

### ISSUE THREAD

**Issue by nlharris** [OBF/homepage#32]
See https://www.open-bio.org/wiki/BOSC_2017_Schedule for example. Can we also do this with gsheets, or would it look nicer if it were in the page style?

**Comment by nlharris** [comment]
I did a quick & dirty version of this by screenshotting our gsheet.

**Comment by yochannah** [comment]
@nlharris could you take a look at the new tablepress plugin I've added? 

<img width="1059" alt="image" src="https://user-images.githubusercontent.com/9271438/59388713-6313d180-8d64-11e9-90d2-ae45fb28a2c5.png">
![image](https://user-images.githubusercontent.com/9271438/59388794-9fdfc880-8d64-11e9-909f-bb503cf1723a.png)

It offers relatively straightforward table editing with no frills to speak of like colour. If you think it's tricky to edit or needs more colours options etc I can see if there is anything else that would work better.

I've left the image in the schedule as well for now but if we;re happy with the table we can remove teh duplication.

**Comment by nlharris** [comment]
The tablepress plugin could be cool but was fancier than I wanted to deal with, so I just ended up putting up screenshots of the schedule overview from a gsheet and that worked well enough.
