### ISSUE TITLE
Link on travel fellowships page(s) to blog posts

### ISSUE THREAD

**Issue by peterjc** [OBF/homepage#38]
https://www.open-bio.org/travel-awards/ does not as far as I can see link to https://www.open-bio.org/category/travel-fellowship/

We could add a link to this paragraph:

> Travel fellowship awardees are required to write a blog post on the OBF blog about their experience attending the event. This should be completed within three weeks after the event ends, and is a prerequisite before the awardee can receive payment.

But likely elsewhere would make sense as well?

**Comment by nlharris** [comment]
I added a link to that paragraph; didn't see any other obvious places.

**Comment by peterjc** [comment]
Thanks Nomi.

This is better, but I think we're not promoting the blog posts enough - both as evidence of the programme's impact, but also as an indication of the scope for potential applicants. How about expanding the opening paragraph?

> # Travel awards
> The Open Bioinformatics Foundation (OBF) sponsors a Travel Fellowship program aimed at increasing diverse participation at events promoting open source bioinformatics software development and open science in the biological research community.

We could add:

> # Travel awards
> The Open Bioinformatics Foundation (OBF) sponsors a Travel Fellowship program aimed at increasing diverse participation at events promoting open source bioinformatics software development and open science in the biological research community - see [blog posts](https://www.open-bio.org/category/travel-fellowship/) of past recipients.

**Comment by nlharris** [comment]
Sure, that sounds good to me. Do you want to add that yourself?

**Comment by peterjc** [comment]
Done, thanks for the comments & feedback Nomi, Hilmar.
