### ISSUE TITLE
Make new page for BOSC 2020

### ISSUE THREAD

**Issue by nlharris** [OBF/homepage#39]
https://www.open-bio.org/events/bosc/ should always point to the latest BOSC page.
The current 2019 page should move to https://www.open-bio.org/events/bosc2019/ and should appear as a new menu item under Events.
The new BOSC 2020 page should say "BOSC 2020" as the leftmost top menu item.
At some point, the BOSC subpages such as Schedule will also need to move to new URLs with 2019 in them so we can keep them accessible while having the more generic URLs point to the latest conference info.
@yochannah maybe at some point we can work on this together?

**Comment by nlharris** [comment]
I think I managed to get this done.
https://www.open-bio.org/events/bosc/ is now the BOSC 2020 page.  i want https://www.open-bio.org/events/bosc/ to always be the current BOSC page. I don’t want visitors to have to do any extra work when they get to that page in order to see the latest info. The generic BOSC page is the “About BOSC” page: https://www.open-bio.org/events/bosc/about/

> The current 2019 page should move to https://www.open-bio.org/events/bosc2019/ and should appear as a new menu item under Events.
I did get the latter to work, but not the former. https://www.open-bio.org/events/bosc/2019/ exists but it shows the BOSC 2020 page. If someone wants to try to fix that, please feel free—otherwise, I think https://www.open-bio.org/events/bosc-2019/ (which points to the 2019 page) is good enough.

> At some point, the BOSC subpages such as Schedule will also need to move to new URLs with 2019 in them so we can keep them accessible while having the more generic URLs point to the latest conference info.
The 2019 schedule is now at https://www.open-bio.org/events/bosc-2019/bosc-2019-schedule/

**Comment by yochannah** [comment]
@nlharris the main new page looks good to me. Looking at some of the other things: 

- I think we found a wordpress feature: it appears that a number at the end of the URL (e.g. https://www.open-bio.org/events/bosc/2019/ ) will just go to its parent's URL - example - random number - https://www.open-bio.org/events/bosc/2034534589/  - and getting it to play nice the way we want it is tricky it seems. It might be easiest to let this one go? 
- is the subpagery all moved? 
- is there anything else I should be doing?

**Comment by nlharris** [comment]
1. Agree; let it go
2. I think the subpages that needed to be moved are moved (but will double-check). Some will instead be revised (e.g., the abstract submission page).
3. I don't think there's anything you need to do on this issue; thanks for asking!
