### ISSUE TITLE
Make past Board meeting minutes easily findable

### ISSUE THREAD

**Issue by hlapp** [OBF/homepage#41]
Past Board meeting minutes are a major artifact of our operations, and it should take people almost no effort to find them. Can we make it a menu item, or at least a major heading on the Board page? Right now (see #13), they're inconspicuously as "here" in a sentence in the first paragraph, and (IMHO) easily missed.

**Comment by nlharris** [comment]
![Screen Shot 2019-11-24 at 11 39 29 AM](https://user-images.githubusercontent.com/348704/69500352-333e2d80-0eaf-11ea-9081-e789222b08a4.png)
Does this look ok?

**Comment by hlapp** [comment]
I think so. We may still want to put all past meeting minutes under a Github repo, but that's a different story from making them easily findable, and it's the latter that is of immediate priority.

**Comment by nlharris** [comment]
Ok, so can we close this issue?

**Comment by hlapp** [comment]
Ah, I hadn't realized that this isn't just a design but implemented. Yes, I think so.
