### ISSUE TITLE
Fix styling of BOSC 2020 and 2018 in "About BOSC" page

### ISSUE THREAD

**Issue by nlharris** [OBF/homepage#42]
I think there must be some postprocessing styling going on that's resulting in this weird formatting:
![Screen Shot 2019-11-23 at 1 50 46 PM](https://user-images.githubusercontent.com/348704/69485751-bcdef400-0df8-11ea-8775-233978f0e583.png)
because I don't see any of that in the html:

`<ul class="bosc-timeline bosc-history"><li><a href="/events/bosc/">BOSC 2020</a> Toronto, Canada (as part of Bioinformatics Community Conference, <a href="https://bcc2020.github.io/">BCC2020</a>)</li><li><a href="/events/bosc-2019/">BOSC 2019</a> Basel, Switzerland (as part of ISMB/ECCB 2019)</li><li><a href="https://www.open-bio.org/wiki/BOSC_2018">BOSC 2018 </a> Portland, Oregon (colocated with the Galaxy Community Conference as part of <a href="https://www.open-bio.org/2018/07/27/gccbosc-2018-post-meeting-report/">GCCBOSC 2018</a>)</li>
`

which should look like this:

> <ul class="bosc-timeline bosc-history"><li><a href="/events/bosc/">BOSC 2020</a> Toronto, Canada (as part of Bioinformatics Community Conference, <a href="https://bcc2020.github.io/">BCC2020</a>)</li><li><a href="/events/bosc-2019/">BOSC 2019</a> Basel, Switzerland (as part of ISMB/ECCB 2019)</li><li><a href="https://www.open-bio.org/wiki/BOSC_2018">BOSC 2018 </a> Portland, Oregon (colocated with the Galaxy Community Conference as part of <a href="https://www.open-bio.org/2018/07/27/gccbosc-2018-post-meeting-report/">GCCBOSC 2018</a>)</li>

**Comment by yochannah** [comment]
Yep, the links were set to display as block and not inline I'll PR this in a sec: 

<img width="643" alt="image" src="https://user-images.githubusercontent.com/9271438/69582061-accd3d00-0fcf-11ea-99dc-c000f1eb5636.png">

**Comment by yochannah** [comment]
fixed by #43
