### ISSUE TITLE
Add GSoC 2020 page to the events sub-menu

### ISSUE THREAD

**Issue by sarthak-sehgal** [OBF/homepage#44]
The GSoC page in the OBF website (https://www.open-bio.org/events/gsoc/) is now up to date. 

As discussed with @yochannah, we are planning to use the main OBF website for project ideas and all updates this time instead of the GitHub templates page (https://obf.github.io/GSoC/). Suggestions are welcome.

I am unable to find the "Appearance" tab in the Wordpress dashboard. The GSoC 2020 page needs to be added in the "Events" sub-menu.

**Comment by yochannah** [comment]
Done - I suspect as an editor maybe you don't have the rights to edit the menu
