### ISSUE TITLE
Update OBF Board officers

### ISSUE THREAD

**Issue by nlharris** [OBF/homepage#45]
https://www.open-bio.org/board/

**Comment by yochannah** [comment]
Whoops - I saw the email for this but not the self assignation, sorry! Came here to update that I'd done the basics - please do double check - @HLWiencko might want to update her bio at some point? 

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/9271438/71788139-90351380-3017-11ea-99fc-f3de34453c5c.png">

**Comment by nlharris** [comment]
Haha, no worries, @yochannah -- you are welcome to tackle any website issues you like!
