### ISSUE TITLE
BOSC 2019 link on Events page goes to main BOSC page

### ISSUE THREAD

**Issue by nlharris** [OBF/homepage#48]
@yochannah, thanks for adding the missing events to the Events page! When you get a chance, can you make the BOSC 2019 link go to https://www.open-bio.org/events/bosc-2019/ rather than https://www.open-bio.org/wp/events/bosc/ (which redirects to the main (now 2020) BOSC page)? Thanks!

**Comment by yochannah** [comment]
Done! :) I'll close the issue for now, but if I've made any mistakes please feel free to re-open
