### ISSUE TITLE
OBF news out of date

### ISSUE THREAD

**Issue by nlharris** [OBF/homepage#5]
https://www-dev1.open-bio.org/blog/ is missing the latest few posts on https://www.open-bio.org/wiki/News
I hope it doesn't have to be hand-updated?

Also (not as major), why do some of the blog posts show up with images and some don't, even though they contain images (e.g. the City of Roses post)?

**Comment by nlharris** [comment]
@yochannah, I hope this is the right tracker to use!
I don't seem to have permission to assign issues.

**Comment by nlharris** [comment]
Latest news list also out of date on home page (https://www-dev1.open-bio.org/)

**Comment by nlharris** [comment]
I think this is the last remaining major issue that I hope can be solved before we go live. (If it's hard to solve, maybe we could hand-update the news lists for now?)

**Comment by yochannah** [comment]
I think this should be fixed now! Thankfully it's just a matter of using the tools menu to export posts with a certain date then importing them to the other wordpress.

**Comment by nlharris** [comment]
Great! Will this process have to be repeated the next time we have a new blog post?

**Comment by yochannah** [comment]
It'll only be an issue if we haven't migrated to the new site next time we write a blog - once we're migrated to the new site we'll need to give everyone access to the new site and stop updating the old news site.
