### ISSUE TITLE
update GSOC pages

### ISSUE THREAD

**Issue by nlharris** [OBF/homepage#59]
the pages under https://www.open-bio.org/events/gsoc/ need some updates - for instance 2020 to 2021 on this page:
https://www.open-bio.org/events/gsoc/gsoc-overview/

**Comment by yochannah** [comment]
@nlharris I updated this page a couple of days ago and I think all mentions of 2020 are appropriate now, but  it might be I missed one - could you screenshot it or describe where it needs to be fixed?

**Comment by nlharris** [comment]
my bad! i found that comment in email and didn't realize it had already been addressed. i should have checked first!
is https://www.open-bio.org/events/gsoc/gsoc-contact/ up to date? it still lists you as an organisation administrator. if that's also still correct, you can close this ticket!
thanks!

**Comment by yochannah** [comment]
It is! 😁
