### ISSUE TITLE
update GSOC pages

### ISSUE THREAD

**Issue by nlharris** [OBF/homepage#61]
the pages under https://www.open-bio.org/events/gsoc/
need some updates - for instance 2020 to 2021 on this page:
https://www.open-bio.org/events/gsoc/gsoc-overview/
(there are probably more places as well)

this shouldn't be my job. who can do this?

**Comment by yochannah** [comment]
Dear Nomi,

I've Ctrl+F searched to try and find mentions of 2020 on the linked page, and all 2020s present are appropriate (e.g. referring to our participation in the past during 2020). If there are other areas that are incorrect that I haven't spotted, I'm happy to fix them :) Please let me know, or just close the issue if you think the mentions of 2020 are okay as is.

**Comment by nlharris** [comment]
hi yo, once again i was just passing on the message without investigating it...i have to admit i did not examine the pages in question. if you think they're good to go, that's good enough for me! thanks for checking!
