### ISSUE TITLE
http://open-bio.org/news/ should point to the blog

### ISSUE THREAD

**Issue by nlharris** [OBF/homepage#62]
should redirect to http://open-bio.org/blog/
instead it gives you "Error establishing a database connection" -- ??
![Screen Shot 2021-06-17 at 3 34 52 PM](https://user-images.githubusercontent.com/348704/122480468-c3583200-cf81-11eb-94e7-8fdcfee4013b.png)

**Comment by peterjc** [comment]
Working now, hopefully a transient error?
