### ISSUE TITLE
OBF page footer doesn't include Slack link

### ISSUE THREAD

**Issue by nlharris** [OBF/homepage#63]
Shouldn't it?
Do we have a Slack invite link that doesn't expire?

**Comment by nlharris** [comment]
I just stumbled across this deficit again and went to make a ticket and saw I'd already made one. Can someone make an OBF slack invite that doesn't expire in 30 days? I don't seem to have permission to do that (or maybe I've forgotten how).

**Comment by hzahroh** [comment]
Do admins or the owner of OBF slack workspace have an option to create a link that doesn't expire in 14-30 days or never expires? Because for discord, the owner has this option.

**Comment by nlharris** [comment]
I'm not sure. I'm not one of the owners. Maybe @hlapp or @peterjc is?

**Comment by peterjc** [comment]
We don’t have a non-expiring Skack invitation link though (just one for the BOSC slack), it seems they stopped offering this ☹️

**Comment by gedankenstuecke** [comment]
With Open Humans we have been using [slackin](https://github.com/rauchg/slackin), which provides a landing page for people to request an invite and the `slackin` app then automatically sends the invite. I haven't personally set it up though, so I'm not sure what exactly the requirements for doing so are.

**Comment by hzahroh** [comment]
Thank you @gedankenstuecke, I'll look into slackin. Thanks Peter for confirming

**Comment by hzahroh** [comment]
The footer now includes Slack link & logo. But I haven't checked slackin 😣🤭 @nlharris 
<img width="475" alt="Screenshot 2022-03-16 at 11 12 19" src="https://user-images.githubusercontent.com/70099457/158520093-5531d59e-b8f3-42e1-9464-77358e9925cd.png">

**Comment by nlharris** [comment]
i'm able to get to the open-bio slack through the logo in the footer now! thanks!!

**Comment by nlharris** [comment]
the slack link in the footer points to https://open-bio.slack.com/
for me that now redirects to https://app.slack.com/client/T0MNP35KR (which doesn't work) but i must have a bad cookie or something, because when i try https://open-bio.slack.com/ in an incognito window it works.
just noting this here for my own future reference. :-)

**Comment by nlharris** [comment]
I discovered that the Slack link in the footer on our website only worked if you already have an account in our workspace, so i generated a new never-expires link and put that in the footer instead.
(To get to the footer in WP: Dashboard -> Appearance -> Widgets
	BOSC Footer links (near the upper right))

**Comment by peterjc** [comment]
Excellent, non-expiring links for both the general OBF slack, and the BOSC one. Nice :)
