### ISSUE TITLE
Broken images for "Upcoming events" on open-bio.org

### ISSUE THREAD

**Issue by nlharris** [OBF/homepage#64]
![Screen Shot 2021-09-26 at 3 11 02 PM](https://user-images.githubusercontent.com/348704/134825949-656ba456-c168-47ce-af93-ee5c6099b426.png)

I have a vague feeling that this may have happened before. Anyone know how to fix it? Maybe @yochannah is the only one?

**Comment by nlharris** [comment]
@hzahroh if you're looking for a starter issue to work on the OBF website, maybe you could take a look at this one. It makes me sad to see those broken images on our home page!

**Comment by hzahroh** [comment]
Sure, let me try @nlharris

**Comment by hzahroh** [comment]
Hi @nlharris, please kindly check whether this is ok now.
<img width="1330" alt="Screenshot 2021-12-07 at 12 44 54" src="https://user-images.githubusercontent.com/70099457/144973363-09c626de-b277-4d07-b912-8ad7a08c2795.png">

**Comment by nlharris** [comment]
That looks great! Thanks! 👍
While you're there, can you change "Upcoming events" to just say "Events" (since in fact the listed events are in the past)?

**Comment by hzahroh** [comment]
It's the least I could do 👍🏻.
For the "upcoming events", I think we need Cpanel access to do that. I have searched everywhere using my WordPress account but couldn't find it.

**Comment by nlharris** [comment]
I'm not sure what that means or how to get it. :-(

**Comment by hzahroh** [comment]
It's the main access to the whole hosting service. We probably need to ask others about who has CPanel access.

**Comment by hlapp** [comment]
> For the "upcoming events", I think we need Cpanel access to do that.

@hzahroh can you say why you think this needs Cpanel access? Regarding Wordpress administration, the only task that needs Cpanel is backup, restore, and upgrade. If you believe the issue is due to files in the filesystem, these are synced from and thus coming from the GitHub repo. But perhaps it's something else?

**Comment by hzahroh** [comment]
@hlapp @nlharris may I take this discussion to our emails or slack?

**Comment by hzahroh** [comment]
"The upcoming events" has been changed to "Events" now. 
![image](https://user-images.githubusercontent.com/70099457/146049143-2cdbc5d2-382c-440e-b06a-2698c4f95264.png)

**Comment by nlharris** [comment]
Thanks so much for fixing this, @hzahroh!
