### ISSUE TITLE
Updating list of retired projects

### ISSUE THREAD

**Issue by cjfields** [OBF/homepage#65]
Per the monthly Board meeting the following should be addressed:

* Updating list of retired projects, missing BioSoap and BioCorba, & standardising language (to match affiliation policy):
  * https://www.open-bio.org/projects/#retired-projects 
  * https://www.open-bio.org/wiki/Projects#In_Memorium

**Comment by peterjc** [comment]
Found some text to help writing a one line description of these two:
https://www.open-bio.org/wiki/Newsletter:2001_Winter#INCOMPLETE_PROJECT_BRIEFS_.26_ANNOUNCEMENT_OF_NEW_PROJECTS

BioCORBA: Aimed to support biological analysis pipelines remotely via [CORBA](https://en.wikipedia.org/wiki/Common_Object_Request_Broker_Architecture) and a choice to programming languages.

BioSOAP: Aimed to support biological analysis pipelines remotely via [SOAP](https://en.wikipedia.org/wiki/SOAP) from BioPerl, BioJava and Ensembl initially.

**Comment by nlharris** [comment]
thanks, peter. https://www.open-bio.org/projects/#retired-projects now includes biosoap and biocorba.
(it wasn't quite as trivial to add them as i expected, because it turns out each project has its own page, but it wasn't too hard.)

**Comment by peterjc** [comment]
Yeah, same idea as how the board members. I've asked on Slack in case anyone can improve the descriptions - ideally someone involved first hand.
