### ISSUE TITLE
Add BOSC 2022 to upcoming events

### ISSUE THREAD

**Issue by nlharris** [OBF/homepage#67]
https://www.open-bio.org/events/

**Comment by nlharris** [comment]
This is done, but https://www.open-bio.org/events/ shows some exposed html. @hzahroh is this something you could fix when you get a chance?

**Comment by hlapp** [comment]
Note that the [event detail page](https://www.open-bio.org/events/bosc-2022/) renders correctly. So it seems to be something that the events overview does with the metadata for the actual events.

**Comment by hzahroh** [comment]
I think we can close this issue now?

**Comment by nlharris** [comment]
No, there's still a problem to be fixed: there is some raw html showing on https://www.open-bio.org/events/. See screenshot below.
![Screen Shot 2022-01-27 at 9 46 41 PM](https://user-images.githubusercontent.com/348704/151494093-4bc65a98-2d60-4c30-8028-b7fbf53f1079.png)
.

**Comment by hlapp** [comment]
I'd argue in agreement with @hzahroh that the issue _can_ and in fact _should_ be closed. The subject is "Add BOSC 2022 to upcoming events", which has arguably been completed.

The remaining issue is arguably a bug in the Wordpress code that does the rendering of the events listing page. We can post that as a separate issue for future investigation, or we can remove the hyperlink to ISMB 2022 from the events metadata. But as the event detail page demonstrates, the metadata for the event, including the link to ISBM 2022, are not somehow incorrect.

**Comment by nlharris** [comment]
Ok, fair enough; indeed, the request in this issue has been satisfied and the formatting thing is a separate issue.

**Comment by nlharris** [comment]
Oh, and guess what? the exposed html turned out to be my error. Now fixed! https://www.open-bio.org/events/
