### ISSUE TITLE
Need a backup strategy

### ISSUE THREAD

**Issue by yochannah** [OBF/homepage#7]
Right now I'm not sure if new content is backed up in any way

**Comment by hlapp** [comment]
Yes, it’s backed up, with one week retention. Do we need longer?

**Comment by yochannah** [comment]
That sounds sufficient. what sort of backup is it taking?

**Comment by hlapp** [comment]
Would you like to inspect the backup files? They are compressed code and database dump archives.

**Comment by yochannah** [comment]
This sounds fine - closing issue as it seems we have things in hand
