### ISSUE TITLE
Update Code of Conduct page

### ISSUE THREAD

**Issue by nlharris** [OBF/homepage#71]
Now that the new CoC has been approved by a membership vote, I think we can update https://www.open-bio.org/code-of-conduct/ to align with https://github.com/OBF/obf-docs/tree/master/code-of-conduct.
@peterjc @gedankenstuecke @hzahroh

**Comment by peterjc** [comment]
How does it look now?

**Comment by nlharris** [comment]
looks good -- i fixed a typo and added a hyperlink for BOSC.
the text "voted on by our members in January 2022" can be made to hyperlink to the blog post i drafted about that (currently still private) once it is posted.

**Comment by peterjc** [comment]
Thanks - shall we leave this issue open until that blog post is live and we've added a link?

**Comment by nlharris** [comment]
yes. i can make the blog post live whenever you (or someone else on the board) approve it.

**Comment by nlharris** [comment]
done
