### ISSUE TITLE
Add Hilya to members of this repo so she can be assigned tickets

### ISSUE THREAD

**Issue by nlharris** [OBF/homepage#72]
@hzahroh is on the list of OBF org members (https://github.com/orgs/OBF/people) but for some reason if I @ her here, GitHub doesn't know about her, and she can't be assigned tickets. I'm not sure I have enough powers to change that. Several of you (including @peterjc, @hlapp, @HLWiencko and even Michael H and Yo) are owners of that org, but I'm just a Member.

**Comment by heuermh** [comment]
I am only a Member not an Owner of the organization, but I can be assigned tickets.

Is it due to membership in the website-maintainers Team?
https://github.com/orgs/OBF/teams/website-maintainers

**Comment by peterjc** [comment]
That sounds likely, adding Hilya to that team now...

**Comment by hlapp** [comment]
Seems to work now.

**Comment by nlharris** [comment]
Thanks, Peter!

**Comment by peterjc** [comment]
Thank @heuermh for the diagnosis

**Comment by hzahroh** [comment]
Thank you, all
