### ISSUE TITLE
https://open-bio.org/events/bosc is mysteriously redirecting to https://www.open-bio.org/2005/01/29/bosc-2005/

### ISSUE THREAD

**Issue by nlharris** [OBF/homepage#77]
For some reason, https://open-bio.org/events/bosc is redirecting to https://www.open-bio.org/2005/01/29/bosc-2005/

This is very bad, because we often give out https://open-bio.org/events/bosc as the main BOSC URL (though https://open-bio.org/events/bosc-2022/ also works).

I don't know when or why this broke, but it'd be great if someone could fix it ASAP! This is a critical period for BOSC, with the abstract submission rapidly approaching.

@yochannah I don't know if this is related to any recent changes made by volunteers

**Comment by nlharris** [comment]
I just discovered that https://open-bio.org/events/bosc redirects to https://www.open-bio.org/2005/01/29/bosc-2005/
but https://open-bio.org/events/bosc/ (with the / at the end) redirects as desired to https://open-bio.org/events/bosc-2022/

**Comment by nlharris** [comment]
i'm trying to add/edit redirect rules, but now https://www.open-bio.org/bosc/ is not redirecting, but showing /cgi-bin/, which is not what is desired!

however, i think i've fixed  https://open-bio.org/events/bosc, which now directs to the 2022 page.

**Comment by hlapp** [comment]
@nlharris can you say where you edited this? It still results in the same incorrect redirect for me, using CURL (which isn't affected by any browser cache).

The redirect is indeed issued by WordPress (not Apache). What seems to be at work is some kind of auto-matching of incomplete URLs. For example, `https://open-bio.org/eve` results in a redirect to `https://www.open-bio.org/event-awards/`.
Likewise, not only ` https://www.open-bio.org/events/bosc` but also `https://www.open-bio.org/events/b` etc all result in redirects to `https://www.open-bio.org/2005/01/29/bosc-2005/`. Perhaps we should simply disable this "feature" if we can.

**Comment by nlharris** [comment]
i edited in tools -> redirection in the WordPress dashboard.

are you saying that if you click on https://open-bio.org/events/bosc it goes to that 2005 page, not to bosc-2022? weird that it would work for me and not for you.

thanks for noting the other cases of weird redirections. i don't know where those are coming from, and whether there's some sort of overarching rule or feature that's causing that to happen.

**Comment by hlapp** [comment]
I am saying that if I curl (on the command line) https://open-bio.org/events/bosc then I get the wrong redirect. I am indeed also getting it by clicking on it. If you don't then it's because of your browser cache. You can verify like this on the command line what others would be seeing:
```sh
$ curl -D -  https://open-bio.org/events/bosc
```

Apparently this is actually a known feature of Wordpress. Unsurprisingly, it has upset more people than just us, and there's now a [plugin to disable it (without also disabling other canonical URL rewriting that Wordpress does for SEO)](https://wordpress.stackexchange.com/questions/144937/disable-only-url-auto-complete-not-the-whole-canonical-url-system).

**Comment by nlharris** [comment]
is that plugin something we should get? i don't feel qualified to install it.

i wanted to go to that 2005 page to edit it and add a big "this probably isn't the page you're looking for -- the current BOSC page is [here]", but i can't even find the page -- it doesn't seem to exist in wp.

i hope someone who understands wp better can unravel this!

**Comment by hlapp** [comment]
It looks like you've now redirected https://www.open-bio.org/2005/01/29/bosc-2005/ to go to the BOSC 2022 page. I've tried (and I saw that you tried) to add a redirect for /events/bosc, but for some reason they don't stick. I don't know why or what's going on there, but the redirect list looks like a complete mess.

**Comment by nlharris** [comment]
yeah, it's a mess. i didn't add most of those, but was afraid to touch them for fear of breaking something else.

**Comment by vdauwera** [comment]
I have some experience dealing with web redirects, lmk if you'd like me to take a look

**Comment by hlapp** [comment]
> I have some experience dealing with web redirects, lmk if you'd like me to take a look

The redirects are issued by WP, based on an algorithm and a table. The problem here is how to make most go away (because they're unhelpful or outright wrong) but keep a few (which correct mistakes or "move" pages). And do so in fuzzy WP.

**Comment by erik-whiting** [comment]
@hlapp it actually looks like this is working now. Am I crazy or are all the dates showing up properly on the news page?

**Comment by nlharris** [comment]
@idoerg maybe this is something you could look into?

**Comment by nlharris** [comment]
This is working now (I think I fixed it but didn't realize right away because the old redirect was cached by my browser)
