### ISSUE TITLE
BOSC 2022 redirect not working consistently

### ISSUE THREAD

**Issue by nlharris** [OBF/homepage#81]
https://www.open-bio.org/events/bosc/ redirects to https://www.open-bio.org/?obf-events=bosc-2022 which is a nearly empty page. What happened to the BOSC page?? This needs to be fixed ASAP!

**Comment by nlharris** [comment]
This is really weird: it seems to behave differently in my two Chrome profiles (work vs personal). In my home profile, https://www.open-bio.org/events/bosc (with or without a final /) redirects correctly to https://www.open-bio.org/events/bosc-2022/. In my work profile, it redirects to https://www.open-bio.org/?obf-events=bosc-2022. (Even if I try to go https://www.open-bio.org/events/bosc-2022/, in my work profile it gets redirected to [https://www.open-bio.org/events/bosc-2022/.](https://www.open-bio.org/?obf-events=bosc-2022). Why would redirects be profile-dependent?? Can others try this and see what happens? @idoerg

**Comment by idoerg** [comment]
https://www.open-bio.org/events/bosc-2022/ brings up the full page  for me.

I'm not sure about the redirect, looking into it.

**Comment by idoerg** [comment]
The redirect to did happen from the drop-down menu, and from the events page.  https://www.open-bio.org/?obf-events=bosc-2022 The problem is reproducible.

But opening in an anonymous browser, or clearing the cookies from open-bio on a non-anonymous browser seemed to do the trick for me. 

So the good news, is that there is a solution, the bad news is I'm not sure why this is happening, and that the solution seems to be client-side. 

Will dig in further.

**Comment by hlapp** [comment]
Page redirection in Wordpress unfortunately seems be a mess. There's also "partial match" redirection, which is probably at least contributing here.

From what I can see, the BOSC About page sits under `/events/bosc-2021/`: https://www.open-bio.org/events/bosc-2021/about/ (and it's link to BOSC 2022 under the timeline goes to BOSC 2021)
There's no corresponding 2022 page (nor arguably should there be one; it should instead be independent of the year).

The link https://www.open-bio.org/events/bosc-2022/ now does resolve correctly to the full page for me. (I think it didn't yesterday?)

**Comment by hlapp** [comment]
> https://www.open-bio.org/events/bosc/ redirects to https://www.open-bio.org/?obf-events=bosc-2022 which is a nearly empty page

This does redirect to the full BOSC 2022 page now for me, and my recollection is that this is the behavior desired, i.e., that it redirect to the page of the current BOSC event. So once the 2023 page exists, it would redirect there.

**Comment by nlharris** [comment]
Now the redirect from /bosc to /bosc-2022 is working from me in both Chrome profiles! Did someone change something? This is really weird.

There are some other issues mentioned here as well (which are not actually tied to this redirect):

- [ ] the BOSC About page sits under /events/bosc-2021/: https://www.open-bio.org/events/bosc-2021/about/
- [x] link on About to BOSC 2022 under the timeline goes to BOSC 2021
- [x] About page has out-of-date text referring to BOSC 2022 as a future event  (not mentioned in this discussion, but something I noticed)
- [ ] The redirect did happen from the drop-down menu -- this is captured in "Events link to BOSC 2022 from OBF home page is broken #80"
