### ISSUE TITLE
Issues with About BOSC page

### ISSUE THREAD

**Issue by nlharris** [OBF/homepage#82]
- [x]  the BOSC About page sits under /events/bosc-2021/: https://www.open-bio.org/events/bosc-2021/about/ . Should be more generic (but what should it be? /events/bosc/about?)
- [x]  link on About to BOSC 2022 under the timeline goes to BOSC 2021
- [x]  About page has various out-of-date bits of text referring to BOSC 2022 as a future event

**Comment by shivprime94** [comment]
hey @nlharris can you please help me out with this exactly what need to be done, so that I can move forward

**Comment by nlharris** [comment]
Thanks so much for your offer to help, @shivprime94! This is something that can only be done by a member of our OBF/BOSC team.
