### ISSUE TITLE
add Mastodon icon+link to OBF and BOSC footers

### ISSUE THREAD

**Issue by nlharris** [OBF/homepage#83]
@peterjc suggested in Slack:
https://www.svgrepo.com/svg/327377/logo-mastodon or https://www.svgrepo.com/svg/314326/mastodon should work, if there isn’t something suitable from the Mastodon GitHub itself…
(https://open-bio.slack.com/x-p21771107671-716702003862-4439549019777/messages/G010B6A057Z/team/ULP46EJPL)   [November 25th at 4:21 PM](https://open-bio.slack.com/x-p21771107671-716702003862-4439549019777/archives/G010B6A057Z/p1669422116535469)
Maybe the black version from https://joinmastodon.org/branding would do, could make it grey at a later point.

**Comment by siddhant7666** [comment]
Hey @nlharris, I can fix this issue, can you please assign this to me. 
And, I am unable to join OBF slack community (above link), as it says you don't have an account in this workspace. Can you please help me with that.

**Comment by nlharris** [comment]
@khokamp maybe you could help with this?

**Comment by nlharris** [comment]
Thanks for doing this, @khokamp!
