### ISSUE TITLE
Change some of the social media icons in the footers

### ISSUE THREAD

**Issue by nlharris** [OBF/homepage#86]
Both OBF and BOSC footer: Remove Twitter
OBF: Add LinkedIn (https://www.linkedin.com/groups/9539620/), Bluesky (https://genomic.social/@OpenBio)
BOSC: Add LinkedIn (https://www.linkedin.com/groups/9539620/), Bluesky (https://genomic.social/@BOSC)

This will result in 7 icons. See also #84 re formatting (may be too hard to fix).

**Comment by nlharris** [comment]
@khokamp is this something you might be able to tackle?

**Comment by nlharris** [comment]
@peterjc said he wants to remove the Twitter icon from the footers, so hopefully he can also make the other changes listed in this issue!

**Comment by peterjc** [comment]
Removing is easy and risk free (this would return to almost the original layout before the Mastodon icon), adding icons gets more tricky...

**Comment by nlharris** [comment]
I mean, someone needs to do it. 🙂

Why don't you remove the twitter icon and save it (you can even name the version) and then try adding the new icons and see how it goes?

Thanks for your help with this!

**Comment by peterjc** [comment]
WordPress admin, left hand column "Appearance", the "Customize" on the current theme, then "Widgets", "Normal Footer links", shown raw HTML to edit (I deleted the Twitter icon), confirm the preview on the right looks OK, click "Publish".

Once we have suitable icons identified for LinkedIn and/or BlueSky, adding them is probably less work than I feared...

**Comment by peterjc** [comment]
The BOSC page footer is currently showing 5+1 icons over two rows, so dropping Twitter should return it to a row of 5. However, that is edited somewhere else...

**Comment by nlharris** [comment]
LinkedIn icon: https://www.flaticon.com/free-icon/linkedin_174857
Bluesky's is strangely elusive: https://www.google.com/search?q=bluesky+social+icon&tbm=isch&ved=2ahUKEwiu1Pr4oqGDAxX6h-4BHdvMCRkQ2-cCegQIABAA&oq=bluesky+social+icon&gs_lcp=CgNpbWcQAzIHCAAQgAQQGDIHCAAQgAQQGDoECCMQJ1CuZ1j0amCLbWgAcAB4AIABP4gBkQKSAQE1mAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=M5OEZe7uJvqPur8P25mnyAE&bih=1238&biw=1415&hl=en
This is the icon that shows up on my phone: https://play-lh.googleusercontent.com/C5Uh9fZ4hAFm7SKrfDBdDZKgvDmDQO06aIBHlmPm3nLubNIz0RIl86E0CtI0RCHvoQva

**Comment by nlharris** [comment]
https://www.open-bio.org/events/bosc-2024/ still has the twitter icon in the footer. i guess you only changed the OBF footer, @peterjc?

**Comment by peterjc** [comment]
See comment above, I didn't find where the BOSC footer is defined.

Update - see #35

**Comment by peterjc** [comment]
Twitter icon now removed from BOSC footer, which lives under appearance, widgets - harder to find than the default footer. See #35 for details.

**Comment by nlharris** [comment]
Thanks -- does something have to be deployed to make that show up on the live site? I'm still seeing the Twitter icon on BOSC pages.

**Comment by peterjc** [comment]
Apparently I missed some saving step?

I changed this last night in Firefox, and the change seemed to be live there this morning, but only until I logged out of WordPress. I also tried in Chrome, again still a Twitter icon.

**Comment by nlharris** [comment]
Good news, now on Chrome the Twitter icon is gone!

Re "Apparently I missed some saving step?" -- I wouldn't assume it was your fault. I feel that since we upgraded WP, it doesn't always save changes reliably. 😔

**Comment by peterjc** [comment]
Seems like a caching issue then? The Twitter icons are gone for me now in Firefox. Which is good, but strange.

**Comment by nlharris** [comment]
So can anyone add the LinkedIn icon + link to the footer? (I wouldn't worry about Bluesky; we don't have much update there yet. Or on Mastodon, for that matter.)

**Comment by nlharris** [comment]
Ok, I added the LinkedIn icon + link to the footer for both OBF and BOSC pages. In the BOSC pages, the icons spill onto two lines; I couldn't find a way to fix that (I tried sizing all the icons down from 60px to 50px, but that didn't help).
